-- EcoMatch Phase 12 — Fix Chat Conversations & Messages Permissions
-- Ensures full read/write access for conversation participants with RLS and safety checks.

-- 1. Ensure conversations table exists
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  buyer_id uuid not null references auth.users(id) on delete cascade,
  seller_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint unique_product_buyer_seller unique(product_id, buyer_id, seller_id)
);

create index if not exists idx_conversations_participants on public.conversations(buyer_id, seller_id);
create index if not exists idx_conversations_product on public.conversations(product_id);

-- 2. Ensure messages table exists
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_messages_conversation on public.messages(conversation_id, created_at asc);

-- 3. Grant Permissions
grant usage on schema public to anon, authenticated;
grant all on public.conversations to anon, authenticated;
grant all on public.messages to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- 4. Enable RLS and setup robust policies
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- Conversations RLS
drop policy if exists "conversations_select" on public.conversations;
create policy "conversations_select"
on public.conversations for select to authenticated
using (auth.uid() = buyer_id or auth.uid() = seller_id);

drop policy if exists "conversations_insert" on public.conversations;
create policy "conversations_insert"
on public.conversations for insert to authenticated
with check (auth.uid() = buyer_id or auth.uid() = seller_id);

drop policy if exists "conversations_update" on public.conversations;
create policy "conversations_update"
on public.conversations for update to authenticated
using (auth.uid() = buyer_id or auth.uid() = seller_id);

-- Messages RLS
drop policy if exists "messages_select" on public.messages;
create policy "messages_select"
on public.messages for select to authenticated
using (
  exists (
    select 1 from public.conversations c
    where c.id = conversation_id
      and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
  )
);

drop policy if exists "messages_insert" on public.messages;
create policy "messages_insert"
on public.messages for insert to authenticated
with check (
  auth.uid() = sender_id
  and exists (
    select 1 from public.conversations c
    where c.id = conversation_id
      and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
  )
);

-- 5. Safe Message Function
create or replace function public.send_safe_message(
  p_conversation_id bigint,
  p_message text,
  p_ai_flag boolean default false,
  p_ai_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  c public.conversations%rowtype;
  clean_message text;
  violation_reason text := null;
  inserted_id bigint;
begin
  select * into c from public.conversations where id = p_conversation_id;
  if not found then
    return jsonb_build_object('allowed', false, 'reason', 'Conversation not found');
  end if;

  if auth.uid() <> c.buyer_id and auth.uid() <> c.seller_id then
    return jsonb_build_object('allowed', false, 'reason', 'Not a participant in this conversation');
  end if;

  clean_message := trim(coalesce(p_message, ''));
  if clean_message = '' then
    return jsonb_build_object('allowed', false, 'reason', 'Empty message');
  end if;

  if clean_message ~* '[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}' then
    violation_reason := 'Email address sharing detected';
  elsif clean_message ~* '(https?://|www\.|wa\.me|t\.me|instagram\.com|facebook\.com|snapchat\.com)' then
    violation_reason := 'External link or social platform redirect detected';
  elsif clean_message ~* '\m[6-9][0-9]{9}\M' then
    violation_reason := 'Phone number sharing detected';
  elsif clean_message ~* '(whats[ ]?app|telegram|insta(gram)?|snap(chat)?|call me|text me|dm me|outside (eco)?match|contact me)' then
    violation_reason := 'Attempt to move the conversation outside EcoMatch';
  elsif p_ai_flag then
    violation_reason := coalesce(nullif(trim(p_ai_reason), ''), 'AI detected an off-platform diversion attempt');
  end if;

  if violation_reason is not null then
    if exists (select 1 from information_schema.tables where table_schema='public' and table_name='chat_safety_events') then
      insert into public.chat_safety_events(conversation_id, sender_id, reason, risk_level)
      values(p_conversation_id, auth.uid(), violation_reason, 'high');
    end if;

    return jsonb_build_object(
      'allowed', false,
      'reason', violation_reason,
      'warning', 'For safety, keep communication and payments inside EcoMatch.'
    );
  end if;

  insert into public.messages(conversation_id, sender_id, message)
  values(p_conversation_id, auth.uid(), clean_message)
  returning id into inserted_id;

  return jsonb_build_object('allowed', true, 'message_id', inserted_id);
end;
$$;

grant execute on function public.send_safe_message(bigint, text, boolean, text) to authenticated, anon;
notify pgrst, 'reload schema';
