"use client";
import React,{createContext,useContext,useEffect,useMemo,useRef,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {EcoMatchWebRTCCallProvider} from '@/lib/trust/call-provider';
import {trustFetch,trustPost} from '@/lib/trust/client';
import {RECORDING_NOTICE} from '@/lib/trust/domain';
import {Phone,PhoneCall,PhoneIncoming,PhoneOff,Mic,MicOff,ShieldCheck,Volume2,VolumeX} from 'lucide-react';
export interface CallInitiateParams {targetUserId:string;targetUserName:string;productId?:number|string|null;productTitle?:string|null;dealId?:string|null;dealCode?:string|null;}
type State='idle'|'calling'|'incoming'|'connected';
const CallingContext=createContext<{initiateCall:(params:CallInitiateParams)=>Promise<void>;activeCallState:State;activeCounterpartyName:string;activeProductTitle:string}>({initiateCall:async()=>{},activeCallState:'idle',activeCounterpartyName:'',activeProductTitle:''});
export const useCalling=()=>useContext(CallingContext);
type Session={id:string;peer:string;name:string;title:string;state:State;offer?:RTCSessionDescriptionInit};
type Signal={callId:string;senderId:string;offer?:RTCSessionDescriptionInit;answer?:RTCSessionDescriptionInit;candidate?:RTCIceCandidateInit};
export default function GlobalCallingProvider({children}:{children:React.ReactNode}){
 const db=useMemo(()=>createClient(),[]),provider=useMemo(()=>new EcoMatchWebRTCCallProvider(),[]);
 const [userId,setUserId]=useState(''),[session,setSession]=useState<Session|null>(null),[pendingStart,setPendingStart]=useState<CallInitiateParams|null>(null),[notice,setNotice]=useState(''),[accepting,setAccepting]=useState(false),[muted,setMuted]=useState(false),[speakerOn,setSpeakerOn]=useState(true),[recording,setRecording]=useState(false),[duration,setDuration]=useState(0);
 const current=useRef<Session|null>(null),userRef=useRef(''),pc=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null),audio=useRef<HTMLAudioElement|null>(null),recorder=useRef<MediaRecorder|null>(null),ice=useRef<RTCIceCandidateInit[]>([]),acceptingRef=useRef(false),started=useRef(0),recordingCall=useRef(''),announcedCall=useRef(''),ringTimer=useRef<number|undefined>(undefined),ringContext=useRef<AudioContext|null>(null),incomingNotification=useRef<Notification|null>(null);
 function update(s:Session|null){current.current=s;setSession(s);}
 function stopRinging(){if(ringTimer.current!==undefined){window.clearInterval(ringTimer.current);ringTimer.current=undefined;}void ringContext.current?.close();ringContext.current=null;incomingNotification.current?.close();incomingNotification.current=null;navigator.vibrate?.(0);}
 function startTone(kind:'incoming'|'ringback'){if(ringTimer.current!==undefined)return;try{const AudioContextCtor=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioContextCtor)return;const context=new AudioContextCtor();ringContext.current=context;void context.resume();const tone=()=>{if(kind==='ringback'){const gain=context.createGain(),first=context.createOscillator(),second=context.createOscillator();first.frequency.value=440;second.frequency.value=480;gain.gain.setValueAtTime(.001,context.currentTime);gain.gain.linearRampToValueAtTime(.08,context.currentTime+.08);gain.gain.setValueAtTime(.08,context.currentTime+1.75);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+2);first.connect(gain);second.connect(gain);gain.connect(context.destination);first.start();second.start();first.stop(context.currentTime+2);second.stop(context.currentTime+2);return;}[587.33,783.99,880,1046.5].forEach((frequency,index)=>{const oscillator=context.createOscillator(),gain=context.createGain(),start=context.currentTime+index*.22;oscillator.type='triangle';oscillator.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(.001,start);gain.gain.linearRampToValueAtTime(.12,start+.05);gain.gain.exponentialRampToValueAtTime(.001,start+.35);oscillator.connect(gain).connect(context.destination);oscillator.start(start);oscillator.stop(start+.35);});};tone();ringTimer.current=window.setInterval(tone,kind==='incoming'?2500:4000);if(kind==='incoming')navigator.vibrate?.([250,150,250,150,400]);}catch{/* A browser may require a previous user interaction before playing a ringtone. */}}
 const startRinging=()=>startTone('incoming');
 function notifyIncoming(){if(typeof Notification==='undefined'||Notification.permission!=='granted'||incomingNotification.current)return;const notification=new Notification('Incoming EcoMatch call',{body:'Open EcoMatch to answer the secure audio call.',tag:'ecomatch-incoming-call',requireInteraction:true});notification.onclick=()=>{window.focus();notification.close();};incomingNotification.current=notification;}
 function cleanup(){stopRinging();window.speechSynthesis?.cancel();if(recorder.current?.state==='recording'){recorder.current.stop();}recorder.current=null;recordingCall.current='';announcedCall.current='';stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(audio.current)audio.current.srcObject=null;pc.current?.close();pc.current=null;ice.current=[];acceptingRef.current=false;setAccepting(false);setRecording(false);setMuted(false);setSpeakerOn(true);setDuration(0);update(null);}
 function announceRecording(s:Session){if(announcedCall.current===s.id||!('speechSynthesis'in window))return;announcedCall.current=s.id;const message=new SpeechSynthesisUtterance('This call is now being recorded for safety.');message.rate=.92;message.volume=1;window.speechSynthesis.speak(message);}
 async function send(peer:string,event:string,payload:Signal){const channel=db.channel(`user-signaling-${peer}`,{config:{private:true}});await new Promise<void>((resolve,reject)=>{channel.subscribe(status=>{if(status==='SUBSCRIBED')resolve();if(['CHANNEL_ERROR','TIMED_OUT'].includes(status))reject(new Error('Secure signaling unavailable'));});});try{await channel.send({type:'broadcast',event,payload});}finally{await db.removeChannel(channel);}}
 async function startRecording(s:Session){
  if(recordingCall.current===s.id||!stream.current)return;
  const verified=await provider.getCallStatus(s.id);if(!verified.recordingAllowed)throw new Error('Recording consent is incomplete');
  if(!MediaRecorder.isTypeSupported('audio/webm')){setNotice('Audio connected. This browser cannot record the supported format.');return;}
  recordingCall.current=s.id;
  // Each participant captures only their microphone; no misleading automatic speaker attribution.
  const chunks:Blob[]=[];let bytes=0;const rec=new MediaRecorder(stream.current,{mimeType:'audio/webm',audioBitsPerSecond:32000});recorder.current=rec;
  rec.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);bytes+=e.data.size;if(bytes>14000000&&rec.state==='recording'){rec.stop();setNotice('Recording limit reached. End this call and start a new one to continue recording.');}}};
  rec.onstop=async()=>{setRecording(false);if(!chunks.length)return;try{const upload=await provider.startRecording(s.id);const {error}=await db.storage.from('call-recordings-private').uploadToSignedUrl(upload.path,upload.token,new Blob(chunks,{type:'audio/webm'}),{contentType:'audio/webm'});if(error)throw error;const result=await trustPost('/api/trust/calls/recording',{action:'analyse',callId:s.id});setNotice(result.status==='COMPLETE'?'Private call recording saved and analysed.':'Recording saved privately; analysis needs retry in Call History.');}catch(e){setNotice(`Recording could not be saved: ${e instanceof Error?e.message:'Please retry'}`);}};
  rec.start(1000);setRecording(true);
 }
 async function connection(s:Session){
  const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});stream.current=media;
  const turnUrls=(process.env.NEXT_PUBLIC_TURN_URLS||'').split(',').map(url=>url.trim()).filter(Boolean);const configuredTurn:RTCIceServer[]=turnUrls.length?[{urls:turnUrls,username:process.env.NEXT_PUBLIC_TURN_USERNAME||'',credential:process.env.NEXT_PUBLIC_TURN_CREDENTIAL||''}]:[];let relayTurn:RTCIceServer[]=[];try{const turn=await trustFetch('/api/trust/turn') as {iceServers?:RTCIceServer[]};if(Array.isArray(turn.iceServers))relayTurn=turn.iceServers;}catch{/* Direct ICE and explicitly configured TURN remain available. */}const iceServers:RTCIceServer[]=[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302','stun:stun.cloudflare.com:3478']},...configuredTurn,...relayTurn];
  const peer=new RTCPeerConnection({iceServers,iceCandidatePoolSize:10});pc.current=peer;
  media.getTracks().forEach(t=>peer.addTrack(t,media));peer.ontrack=e=>{if(audio.current){audio.current.srcObject=e.streams[0]||new MediaStream([e.track]);audio.current.muted=false;audio.current.volume=1;audio.current.play().catch(()=>setNotice('Tap the audio player once to hear this call.'));}};
  peer.onicecandidate=e=>{if(e.candidate)void send(s.peer,'ICE_CANDIDATE',{callId:s.id,senderId:userRef.current,candidate:e.candidate.toJSON()}).catch(e=>setNotice(e.message));};
  peer.onconnectionstatechange=()=>{if(peer.connectionState==='connected')stopRinging();if(peer.connectionState==='failed')setNotice('Audio connection failed. A TURN relay is required for this network.');};return peer;
 }
 async function waitForIceGathering(peer:RTCPeerConnection,timeoutMs=3500){if(peer.iceGatheringState==='complete')return;await new Promise<void>(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;window.clearTimeout(timer);peer.removeEventListener('icegatheringstatechange',check);resolve();};const check=()=>{if(peer.iceGatheringState==='complete')finish();};const timer=window.setTimeout(finish,timeoutMs);peer.addEventListener('icegatheringstatechange',check);});}
 async function durableOffer(s:Session){for(let attempt=0;attempt<25;attempt++){const status=await provider.getCallStatus(s.id);const offer=status.call.offer as RTCSessionDescriptionInit|undefined;if(offer?.sdp)return offer;await new Promise(resolve=>window.setTimeout(resolve,120));}if(s.offer?.sdp)return s.offer;throw new Error('Call setup did not finish. Please retry.');}
 async function flush(){const peer=pc.current;if(!peer?.remoteDescription)return;for(const candidate of ice.current.splice(0)){try{await peer.addIceCandidate(candidate);}catch{/* The persisted SDP already contains gathered candidates; duplicate broadcasts are safe to ignore. */}}}
 async function applyAnswer(s:Session,answer:RTCSessionDescriptionInit){if(s.state!=='calling'||!pc.current||pc.current.currentRemoteDescription)return;await pc.current.setRemoteDescription(answer);await flush();stopRinging();started.current=Date.now();update({...s,state:'connected'});announceRecording(s);void startRecording(s).catch(e=>setNotice(e instanceof Error?e.message:'Recording could not start'));}
 async function initiateCall(p:CallInitiateParams){
  if(current.current||pendingStart){setNotice('End your current call first.');return;}if(!userRef.current){setNotice('Please sign in to call.');return;}setPendingStart(p);
 }
 async function placeCall(p:CallInitiateParams){
  setPendingStart(null);
  try{const {callId}=await provider.startCall({...p});const s:Session={id:callId,peer:p.targetUserId,name:p.targetUserName,title:p.productTitle||'',state:'calling'};update(s);startTone('ringback');const peer=await connection(s);const offer=await peer.createOffer();await peer.setLocalDescription(offer);void send(s.peer,'CALL_OFFER',{callId,senderId:userRef.current,offer}).catch(()=>{});await waitForIceGathering(peer);const completeOffer=peer.localDescription?.toJSON()||offer;await trustPost('/api/trust/calls',{action:'save_offer',callId,offer:completeOffer});void send(s.peer,'CALL_OFFER',{callId,senderId:userRef.current,offer:completeOffer}).catch(()=>{});}catch(e){const failed=current.current as Session|null;if(failed)await provider.endCall(failed.id).catch(()=>{});cleanup();setNotice(e instanceof Error?e.message:'Call unavailable');}
 }
 async function accept(){const s=current.current;if(!s||acceptingRef.current)return;acceptingRef.current=true;setAccepting(true);
  try{stopRinging();const peer=await connection(s);const offer=await durableOffer(s);await peer.setRemoteDescription(offer);await flush();const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await waitForIceGathering(peer);const completeAnswer=peer.localDescription?.toJSON()||answer;await provider.acceptCall(s.id);await trustPost('/api/trust/calls',{action:'save_answer',callId:s.id,answer:completeAnswer});void send(s.peer,'CALL_ANSWER',{callId:s.id,senderId:userRef.current,answer:completeAnswer}).catch(()=>{});started.current=Date.now();update({...s,state:'connected'});announceRecording(s);void startRecording(s).catch(e=>setNotice(e instanceof Error?e.message:'Recording could not start'));}catch(e){setNotice(e instanceof Error?e.message:'Unable to accept');await provider.endCall(s.id).catch(()=>{});cleanup();}finally{acceptingRef.current=false;setAccepting(false);}
 }
 async function end(reject=false){const s=current.current;if(!s)return;try{void send(s.peer,'CALL_END',{callId:s.id,senderId:userRef.current}).catch(()=>{});await (reject?provider.rejectCall(s.id):provider.endCall(s.id));}catch(e){setNotice(e instanceof Error?e.message:'Could not update call');}finally{cleanup();}}
 useEffect(()=>{let alive=true;void db.auth.getUser().then(({data})=>{if(alive){userRef.current=data.user?.id||'';setUserId(userRef.current);}});const {data:{subscription}}=db.auth.onAuthStateChange((_event,s)=>{userRef.current=s?.user.id||'';setUserId(userRef.current);});return()=>{alive=false;subscription.unsubscribe();};},[db]);
 useEffect(()=>{
  if(!userId)return;
  const channel=db.channel(`user-signaling-${userId}`,{config:{private:true}});
  const handle=async(event:string,p:Signal)=>{try{
   if(event==='CALL_OFFER'){
    if(current.current)return;const verified=await provider.getCallStatus(p.callId);if(verified.call.caller_id!==p.senderId||verified.call.receiver_id!==userId||verified.call.status!=='RINGING')return;
    update({id:p.callId,peer:p.senderId,name:'EcoMatch member',title:'Safe in-app call',state:'incoming',offer:p.offer});startRinging();notifyIncoming();return;
   }
   const s=current.current;if(!s||p.callId!==s.id||p.senderId!==s.peer)return;
   if(event==='ICE_CANDIDATE'&&p.candidate){ice.current.push(p.candidate);await flush();}
   if(event==='CALL_ANSWER'&&p.answer&&s.state==='calling'){const v=await provider.getCallStatus(s.id);if(!v.recordingAllowed)return;await applyAnswer(s,p.answer);}
   if(event==='CALL_END'){await provider.endCall(s.id);cleanup();}
  }catch(e){setNotice(e instanceof Error?e.message:'Call signaling failed');}};
  for(const event of ['CALL_OFFER','CALL_ANSWER','ICE_CANDIDATE','CALL_END'])channel.on('broadcast',{event},({payload})=>{void handle(event,payload as Signal);});
  channel.subscribe();return()=>{void db.removeChannel(channel);};
  // Handler reads active call and media refs, not render-time session snapshots.
  // eslint-disable-next-line react-hooks/exhaustive-deps
 },[userId,db,provider]);
 useEffect(()=>{if(!session)return;const timer=setInterval(()=>{if(current.current?.state==='connected')setDuration(Math.floor((Date.now()-started.current)/1000));},1000);const timeout=session.state==='calling'?setTimeout(()=>{void end();setNotice('No answer. Call ended.');},35000):undefined;return()=>{clearInterval(timer);clearTimeout(timeout);};
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[session?.id,session?.state]);
 useEffect(()=>{if(!userId)return;const checkCall=async()=>{try{const data=await trustFetch('/api/trust/calls') as {calls?:Array<{id:string;caller_id:string;receiver_id:string;status:string;offer?:RTCSessionDescriptionInit;answer?:RTCSessionDescriptionInit}>};const call=data.calls?.find(c=>c.receiver_id===userId&&c.status==='RINGING'&&c.offer);if(!current.current&&call){update({id:call.id,peer:call.caller_id,name:'EcoMatch member',title:'Safe in-app call',state:'incoming',offer:call.offer});startRinging();notifyIncoming();}const active=current.current;if(active?.state==='incoming'&&call?.id===active.id&&call.offer?.sdp&&call.offer.sdp!==active.offer?.sdp)update({...active,offer:call.offer});if(active?.state==='calling'){const answered=data.calls?.find(c=>c.id===active.id&&c.answer);if(answered?.answer)await applyAnswer(active,answered.answer);}}catch{/* Broadcast remains the primary low-latency path. */}};void checkCall();const timer=setInterval(()=>void checkCall(),350);return()=>clearInterval(timer);
 // Polling intentionally reads live refs; recreating it for render-local callbacks would cause duplicate requests.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[userId]);
 async function report(){const s=current.current;if(!s)return;const description=window.prompt('Describe the call safety concern.');if(!description)return;const {error}=await db.from('communication_reports').insert({reporter_id:userId,reported_user_id:s.peer,call_id:s.id,reason:'Call safety concern',description,status:'PENDING'});setNotice(error?error.message:'Report sent to the safety team.');}
 const formattedDuration=`${String(Math.floor(duration/60)).padStart(2,'0')}:${String(duration%60).padStart(2,'0')}`;
 return <CallingContext.Provider value={{initiateCall,activeCallState:session?.state||'idle',activeCounterpartyName:session?.name||'',activeProductTitle:session?.title||''}}>
  {children}
  <audio ref={audio} autoPlay playsInline className="hidden"/>
  {notice&&<div role="status" className="fixed left-1/2 top-20 z-[100] w-[min(92vw,440px)] -translate-x-1/2 rounded-2xl border border-amber-400/30 bg-[#061d15]/95 p-4 text-sm text-amber-100 shadow-2xl backdrop-blur-xl">{notice}<button className="ml-3 min-h-12 underline" onClick={()=>setNotice('')}>Dismiss</button></div>}
  {pendingStart&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/80 p-4 backdrop-blur-md" role="dialog" aria-modal="true" aria-label="Call recording disclosure"><div className="w-full max-w-sm rounded-3xl border border-amber-400/30 bg-[#071b14] p-6 text-white shadow-2xl"><div className="flex items-center gap-3"><ShieldCheck className="h-8 w-8 text-amber-300"/><div><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300">Before you call</p><h2 className="text-xl font-black">Safety recording notice</h2></div></div><p className="mt-4 text-sm leading-6 text-white/80">{RECORDING_NOTICE}</p><p className="mt-3 rounded-2xl border border-white/10 bg-white/5 p-3 text-xs leading-5 text-white/65">Selecting “Start call” confirms that you have read this notice. The other participant sees the same notice before accepting, and both devices hear a recording announcement after connection.</p><div className="mt-6 grid grid-cols-2 gap-3"><button className="min-h-12 rounded-2xl border border-white/15 bg-white/5 font-bold text-white/80" onClick={()=>setPendingStart(null)}>Cancel</button><button className="min-h-12 rounded-2xl bg-emerald-400 font-black text-[#03140e] shadow-lg shadow-emerald-500/20" onClick={()=>void placeCall(pendingStart)}><Phone className="mr-2 inline h-4 w-4"/>Start call</button></div></div></div>}
  {session?.state==='calling'&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/80 p-4 backdrop-blur-md"><div className="w-full max-w-sm rounded-3xl border border-sky-500/30 bg-[#061922] p-7 text-center text-white shadow-2xl"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border border-sky-400/40 bg-sky-500/20 shadow-[0_0_30px_rgba(56,189,248,.35)]"><PhoneCall className="h-9 w-9 animate-bounce text-sky-300"/></div><h2 className="mt-5 text-xl font-black">Calling {session.name}…</h2>{session.title&&<p className="mt-2 text-sm text-sky-200">Regarding: {session.title}</p>}<div className="mt-4 flex items-center justify-center gap-2 text-sm font-bold text-sky-300"><Volume2 className="h-4 w-4 animate-pulse"/>Ringing · secure audio</div><button className="mt-7 min-h-12 rounded-2xl bg-red-600 px-7 font-black text-white" onClick={()=>void end()}><PhoneOff className="mr-2 inline h-4 w-4"/>Cancel call</button></div></div>}
  {session?.state==='incoming'&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/85 p-4 backdrop-blur-lg" role="dialog" aria-modal="true" aria-label="Incoming EcoMatch call"><div className="w-full max-w-sm rounded-3xl border border-emerald-400/40 bg-[#051c14] p-7 text-center text-white shadow-[0_0_45px_rgba(16,185,129,.3)]"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border-2 border-emerald-400 bg-emerald-500/20 shadow-[0_0_30px_rgba(16,185,129,.45)]"><PhoneIncoming className="h-9 w-9 animate-pulse text-emerald-300"/></div><p className="mt-4 text-xs font-black uppercase tracking-[.18em] text-emerald-300">Incoming EcoMatch call</p><h2 className="mt-2 text-2xl font-black">{session.name}</h2>{session.title&&<p className="mt-1 text-sm text-white/70">{session.title}</p>}<div className="mt-4 flex items-center justify-center gap-2 text-sm font-bold text-emerald-300"><Volume2 className="h-4 w-4 animate-bounce"/>{accepting?'Connecting secure audio…':'Ringing · private in-app audio'}</div><p className="mt-4 rounded-2xl border border-white/10 bg-white/5 p-3 text-left text-xs leading-5 text-white/70">{RECORDING_NOTICE} Accepting confirms you have read this notice.</p><div className="mt-6 grid grid-cols-2 gap-3"><button disabled={accepting} className="min-h-12 rounded-2xl border border-red-400/30 bg-red-500/15 font-bold text-red-200 disabled:opacity-50" onClick={()=>void end(true)}><PhoneOff className="mr-2 inline h-4 w-4"/>Decline</button><button disabled={accepting} className="min-h-12 rounded-2xl bg-emerald-400 font-black text-[#03140e] shadow-lg shadow-emerald-500/25 disabled:cursor-wait disabled:opacity-70" onClick={()=>void accept()}><Phone className="mr-2 inline h-4 w-4"/>{accepting?'Connecting…':'Accept call'}</button></div></div></div>}
  {session?.state==='connected'&&<section className="fixed bottom-5 right-4 z-[80] w-[min(92vw,390px)] rounded-3xl border border-emerald-400/40 bg-[#061f17]/95 p-5 text-white shadow-2xl backdrop-blur-xl" aria-label="Connected EcoMatch call"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-500/20"><Volume2 className="h-5 w-5 text-emerald-300"/></div><div><h2 className="font-black">{session.name}</h2><p className="font-mono text-sm text-emerald-300">● Connected · {formattedDuration}</p></div></div><div className="rounded-full border border-red-400/25 bg-red-500/10 px-3 py-1 text-[10px] font-black text-red-200">{recording?'● REC':'SECURE'}</div></div><p className="mt-3 text-xs leading-5 text-white/60">Recording notice was announced when the call connected.</p><div className="mt-4 flex items-center justify-between border-t border-white/10 pt-4"><div className="flex gap-2"><button aria-label={muted?'Unmute microphone':'Mute microphone'} className="flex h-12 w-12 items-center justify-center rounded-xl border border-white/10 bg-white/5" onClick={()=>{stream.current?.getAudioTracks().forEach(track=>track.enabled=muted);setMuted(!muted);}}>{muted?<MicOff/>:<Mic/>}</button><button aria-label={speakerOn?'Mute speaker':'Enable speaker'} className="flex h-12 w-12 items-center justify-center rounded-xl border border-white/10 bg-white/5" onClick={()=>{if(audio.current)audio.current.muted=speakerOn;setSpeakerOn(!speakerOn);}}>{speakerOn?<Volume2/>:<VolumeX/>}</button><button className="min-h-12 px-3 text-xs font-bold text-amber-200 underline" onClick={()=>void report()}>Report</button></div><button className="min-h-12 rounded-xl bg-red-600 px-5 font-black" onClick={()=>void end()}><PhoneOff className="mr-2 inline h-4 w-4"/>End</button></div></section>}
 </CallingContext.Provider>;
}
