"use client";
import {useCallback,useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {trustFetch,trustPost} from '@/lib/trust/client';
import {Truck,ShieldCheck,RefreshCw} from 'lucide-react';
import {generateQrSvg} from '@/lib/trust/qr';
import DeliveryEstimatePreview from '@/components/DeliveryEstimatePreview';
type Evidence={id:string;stage:string;photos:string[];video_path:string;review_status:string;ai_result:unknown;created_at:string};
type Data={deal:{id:string;buyer_id:string;seller_id:string;status:string;secure_state:string|null;secure_version:number;secure_demo:boolean};delivery:{pickup?:{address:string};dropoff?:{address:string};provider_status?:string}|null;quote:{product_paise:number;delivery_paise:number;service_paise:number;total_paise:number;deposit_paise:number;distance_km:number;expires_at:string}|null;payments:{id:string;payer_id:string;kind:string;status:string;amount_paise:number}[];deposit:{status:string;amount_paise:number;deducted_paise:number}|null;evidence:Evidence[];timeline:{id:string;event_type:string;created_at:string}[]};
const rupees=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n/100);
const button='min-h-12 rounded-xl bg-lime-300 px-4 py-3 text-sm font-bold text-[#062016] disabled:opacity-40';
export default function SecureDeliveryPanel({dealId,userId,admin=false,onModeChange}:{dealId:string;userId:string;admin?:boolean;onModeChange?:(secure:boolean)=>void}){
 const [previewOpen,setPreviewOpen]=useState(false);
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[address,setAddress]=useState(''),[lat,setLat]=useState(''),[lng,setLng]=useState(''),[photos,setPhotos]=useState<File[]>([]),[video,setVideo]=useState<File|null>(null),[token,setToken]=useState<{url:string;otp:string;expiresAt:string}|null>(null),[reason,setReason]=useState('Wrong Product'),[description,setDescription]=useState(''),[reviewReason,setReviewReason]=useState(''),[refund,setRefund]=useState(''),[deduction,setDeduction]=useState(''),[showDispute,setShowDispute]=useState(false);
 const load=useCallback(async()=>{try{const d:Data=await trustFetch(`/api/trust/deals/${dealId}`);setData(d);setError('');onModeChange?.(!!d.deal.secure_state);}catch(e){setError(e instanceof Error?e.message:'Delivery unavailable');}},[dealId,onModeChange]);
 useEffect(()=>{
  let active = true;
  trustFetch(`/api/trust/deals/${dealId}`).then((d: unknown)=>{
    if (!active) return;
    const dataObj = d as Data;
    setData(dataObj);
    setError('');
    onModeChange?.(!!dataObj.deal.secure_state);
  }).catch((e: unknown)=>{
    if (!active) return;
    setError(e instanceof Error?e.message:'Delivery unavailable');
  });
  return ()=>{ active = false; };
 },[dealId,onModeChange]);
 async function act(action:string,extra:Record<string,unknown>={}){if(!data)return;setBusy(true);setError('');try{const result=await trustPost(`/api/trust/deals/${dealId}`,{action,version:data.deal.secure_version,key:crypto.randomUUID(),...extra});if(action==='issue_token')setToken(result);else setNotice('Update saved.');await load();return result;}catch(e){setError(e instanceof Error?e.message:'Update failed');await load();}finally{setBusy(false);}}
 async function upload(stage:string){if(photos.length<3||photos.length>5||!video){setError('Choose 3–5 photos and one short video.');return;}if([...photos,video].reduce((n,f)=>n+f.size,0)>18000000){setError('Keep all evidence under 18 MB.');return;}setBusy(true);try{const paths=[];for(const file of [...photos,video]){const signed=await trustPost('/api/trust/media',{dealId,stage,mimeType:file.type});const {error}=await createClient().storage.from('exchange-evidence').uploadToSignedUrl(signed.path,signed.token,file,{contentType:file.type});if(error)throw error;paths.push(signed.path);}await act('evidence',{stage,photos:paths.slice(0,-1),videoPath:paths.at(-1)});setPhotos([]);setVideo(null);}catch(e){setError(e instanceof Error?e.message:'Upload failed');}finally{setBusy(false);}}
 async function savedLocation(){const {data:{user}}=await createClient().auth.getUser();if(!user)return;const {data:p}=await createClient().from('profiles').select('location_name,latitude,longitude').eq('id',user.id).single();if(p){setAddress(p.location_name||'');setLat(String(p.latitude??''));setLng(String(p.longitude??''));}}
 async function view(path:string){try{const r=await trustPost('/api/trust/media',{operation:'read',dealId,path});window.open(r.signedUrl,'_blank','noopener,noreferrer');}catch(e){setError(e instanceof Error?e.message:'Evidence unavailable');}}
 const state=data?.deal.secure_state,buyer=data?.deal.buyer_id===userId,seller=data?.deal.seller_id===userId;
 const journey=[['Offer accepted','accepted'],['Route & payment','DELIVERY_QUOTED'],['Pickup evidence','PICKUP_VERIFIED'],['Safe handover','BUYER_CONFIRMATION_PENDING'],['Ledger complete','COMPLETED']];
 const stage=state==='RETURN_DELIVERED'&&seller?'return':state==='DISPUTED'?'dispute':seller&&['PICKUP_EVIDENCE_PENDING','PICKUP_REVIEW_REQUIRED'].includes(state||'')?'pickup':buyer&&['DELIVERY_EVIDENCE_PENDING','DELIVERY_REVIEW_REQUIRED'].includes(state||'')?'delivery':null;
 const advance:Record<string,string>={LOGISTICS_BOOKED:'DRIVER_ASSIGNED',PICKUP_COMPLETED:'IN_TRANSIT',IN_TRANSIT:'DELIVERY_EVIDENCE_PENDING'};
 const returnAdvance:Record<string,string>={RETURN_REQUESTED:'RETURN_BOOKING',RETURN_BOOKING:'RETURN_PICKUP',RETURN_PICKUP:'RETURN_IN_TRANSIT',RETURN_IN_TRANSIT:'RETURN_DELIVERED'};
 return <section className="my-8 rounded-3xl border border-emerald-300/30 bg-[#062016] p-5 text-white sm:p-8"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-widest text-lime-300">SAFE EXCHANGE PROTOCOL</p><h2 className="mt-2 flex items-center gap-3 text-2xl font-bold"><Truck/>EcoMatch Secure Delivery</h2></div><button aria-label="Refresh delivery" className="min-h-12 min-w-12" onClick={()=>void load()}><RefreshCw/></button></div>
 <div className="my-5 grid gap-2 sm:grid-cols-5">{journey.map(([label,key],index)=>{const active=state===key||(!state&&index===0)||(['FULFILMENT_SELECTED','SELLER_DEPOSIT_PENDING','BUYER_PAYMENT_PENDING','DRIVER_ASSIGNED','PICKUP_COMPLETED','PICKUP_EVIDENCE_PENDING','PICKUP_REVIEW_REQUIRED','IN_TRANSIT','DELIVERY_EVIDENCE_PENDING','DELIVERY_REVIEW_REQUIRED','PAYMENT_RELEASE_PENDING'].includes(state||'')&&index>0);return <div key={key} className={`rounded-xl border p-3 text-xs ${active?'border-lime-300/60 bg-lime-300/10 text-lime-100':'border-white/10 text-white/45'}`}><strong>0{index+1}</strong><p className="mt-1 font-semibold">{label}</p></div>})}</div>
 <details onToggle={e=>setPreviewOpen(e.currentTarget.open)} className="my-5 rounded-2xl border border-lime-300/30 p-4"><summary className="min-h-12 cursor-pointer py-3 font-bold text-lime-300">Plan delivery and review checkout</summary><p className="mb-4 text-sm text-slate-300">The buyer chooses a destination; seller pickup and agreed item value are securely sourced from the deal. It opens a payment simulation until a gateway is connected.</p>{previewOpen&&<DeliveryEstimatePreview dealId={dealId}/>}</details>
 {error&&<p role="alert" className="my-4 rounded-xl bg-amber-100 p-4 text-amber-950">{!data ? "Live delivery booking is currently unavailable. You can still explore the estimate and payment preview above. No payment or booking will be made." : error}</p>}{notice&&<p role="status" className="my-3 text-lime-200">{notice}</p>}
 {!data&&<a href="#self-pickup" className="inline-flex min-h-12 items-center rounded-xl border border-white/30 px-4 py-3">Meet Seller / Self Pickup</a>}
 {!state&&data&&<><p className="my-4">How would you like to receive this product?</p><div className="flex flex-wrap gap-3"><button className={button} disabled={busy||!buyer||data?.deal.status!=='accepted'} onClick={()=>void act('select_delivery')}>EcoMatch Secure Delivery</button><a href="#self-pickup" className="min-h-12 rounded-xl border border-white/30 px-4 py-3">Meet Seller / Self Pickup</a></div><p className="mt-3 text-sm text-white/60">Secure Delivery becomes available to the buyer after the seller accepts the deal. Both participants confirm their addresses privately.</p></>}
 {state&&data&&<><div className="my-5 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-4 py-2 text-sm">{state.replaceAll('_',' ')}</span>{data.deal.secure_demo&&<strong className="rounded-full bg-amber-200 px-4 py-2 text-sm text-amber-950">SHOWCASE MODE · no live payment or carrier booking</strong>}</div>
 {['FULFILMENT_SELECTED','DELIVERY_QUOTED'].includes(state)&&!admin&&<div className="my-5 space-y-3 rounded-2xl bg-white/5 p-4"><h3 className="font-bold">Confirm your {seller?'pickup':'delivery'} location</h3><p className="text-sm text-white/70">Exact addresses are visible only to this transaction and authorised administrators.</p><label className="block">Complete address<input value={address} onChange={e=>setAddress(e.target.value)} className="mt-1 min-h-12 w-full rounded-lg bg-white p-3 text-black"/></label><div className="grid grid-cols-2 gap-3"><label>Latitude<input value={lat} onChange={e=>setLat(e.target.value)} type="number" step="any" className="mt-1 min-h-12 w-full rounded-lg bg-white p-3 text-black"/></label><label>Longitude<input value={lng} onChange={e=>setLng(e.target.value)} type="number" step="any" className="mt-1 min-h-12 w-full rounded-lg bg-white p-3 text-black"/></label></div><div className="flex flex-wrap gap-3"><button className={button} onClick={()=>void savedLocation()}>Use saved location</button><button className={button} onClick={()=>navigator.geolocation.getCurrentPosition(p=>{setLat(String(p.coords.latitude));setLng(String(p.coords.longitude));},()=>setError('Location permission was not granted. Enter coordinates manually.'))}>Use my current location</button><button className={button} disabled={busy} onClick={()=>void act('address',{location:{address,latitude:lat,longitude:lng}})}>Confirm address</button></div></div>}
 <div className="my-4 grid gap-3 sm:grid-cols-2"><p>Pickup: {data.delivery?.pickup?.address||'Awaiting seller confirmation'}</p><p>Delivery: {data.delivery?.dropoff?.address||'Awaiting buyer confirmation'}</p></div>
 {buyer&&['FULFILMENT_SELECTED','DELIVERY_QUOTED'].includes(state)&&<button className={button} disabled={busy} onClick={()=>void act('quote')}>Get delivery estimate</button>}
 {data.quote&&<div className="my-5 rounded-2xl bg-white/5 p-5"><h3 className="mb-3 text-lg font-bold">Transparent checkout</h3>{[['Product',data.quote.product_paise],['Delivery estimate',data.quote.delivery_paise],['EcoMatch logistics/service buffer',data.quote.service_paise],['Total payable',data.quote.total_paise]].map(([label,value])=><div key={String(label)} className="flex justify-between gap-3 border-b border-white/10 py-2"><span>{label}</span><strong>{rupees(Number(value))}</strong></div>)}<p className="mt-4">Refundable Seller Security Deposit: <strong>{rupees(data.quote.deposit_paise)}</strong></p><p className="text-sm text-white/70">Held separately to cover reviewed return costs. Refunded after successful delivery. A complaint alone never forfeits this deposit.</p><p className="mt-2 text-xs opacity-60">Estimate valid until {new Date(data.quote.expires_at).toLocaleString()}. This is a payment hold, subject to the configured provider.</p></div>}
 <div className="flex flex-wrap gap-3">{buyer&&state==='DELIVERY_QUOTED'&&<button className={button} disabled={busy} onClick={()=>void act('buyer_order')}>Create payment request</button>}{seller&&state==='SELLER_DEPOSIT_PENDING'&&!data.payments.some(p=>p.kind==='deposit')&&<button className={button} disabled={busy} onClick={()=>void act('deposit_order')}>Confirm refundable security deposit</button>}{data.deal.secure_demo&&data.payments.some(p=>p.payer_id===userId&&p.status==='PENDING')&&<button className={button} disabled={busy} onClick={()=>void act('demo_pay')}>Mark showcase payment confirmed</button>}{seller&&state==='PICKUP_VERIFIED'&&<button className={button} disabled={busy} onClick={()=>void act('book')}>Send dispatch request to operations</button>}{data.deal.secure_demo&&advance[state]&&<button className={button} disabled={busy} onClick={()=>void act('demo_tracking',{state:advance[state]})}>Advance showcase tracking: {advance[state].replaceAll('_',' ')}</button>}{((seller&&state==='DRIVER_ASSIGNED')||(buyer&&state==='BUYER_CONFIRMATION_PENDING'))&&<button className={button} disabled={busy} onClick={()=>void act('issue_token',{purpose:seller?'pickup':'delivery'})}>Create handover link & OTP</button>}{buyer&&state==='BUYER_CONFIRMATION_PENDING'&&<button className={button} disabled={busy} onClick={()=>void act('buyer_confirm')}>Confirm item received</button>}{state==='PAYMENT_RELEASE_PENDING'&&<button className={button} disabled={busy} onClick={()=>void act('settle')}>Complete settlement & ownership transfer</button>}{!admin&&!['COMPLETED','RETURNED','CANCELLED','EXPIRED','DISPUTED'].includes(state)&&<button className="min-h-12 rounded-xl border border-amber-300 px-4" onClick={()=>setShowDispute(!showDispute)}>Report a Problem</button>}{['FULFILMENT_SELECTED','DELIVERY_QUOTED','BUYER_PAYMENT_PENDING'].includes(state)&&<button className="min-h-12 px-3 underline" disabled={busy} onClick={()=>void act('cancel')}>Cancel unpaid delivery</button>}</div>
 {token&&<div className="my-5 rounded-2xl bg-lime-100 p-5 text-black"><div className="flex flex-col sm:flex-row items-center gap-6"><div className="shrink-0 overflow-hidden rounded-xl bg-white p-2 shadow" dangerouslySetInnerHTML={{__html:generateQrSvg(typeof window==='undefined'?token.url:`${window.location.origin}${token.url}`,160)}}/><div className="space-y-1"><p className="font-semibold">Scan QR or share link with the delivery partner:</p><a className="break-all text-xs font-mono underline" href={token.url} target="_blank" rel="noreferrer">{typeof window==='undefined'?'':window.location.origin}{token.url}</a><p className="mt-2 text-3xl font-black tracking-widest text-[#062016]">OTP: {token.otp}</p><p className="text-xs text-black/70">Expires {new Date(token.expiresAt).toLocaleTimeString()}. Creating a new code revokes the previous unused code.</p></div></div></div>}
 {showDispute&&<div className="my-5 space-y-3"><label>Problem<select className="min-h-12 w-full rounded-xl bg-white p-3 text-black" value={reason} onChange={e=>setReason(e.target.value)}>{['Wrong Product','Damaged Product','Different From Listing','Missing Parts','Quantity Mismatch','Other'].map(r=><option key={r}>{r}</option>)}</select></label><textarea aria-label="Describe the problem" className="w-full rounded-xl bg-white p-3 text-black" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the problem (at least 10 characters)"/><button className={button} disabled={busy||description.length<10} onClick={()=>void act('dispute',{reason,description}).then(()=>setShowDispute(false))}>Open dispute & freeze settlement</button></div>}
 {stage&&<div className="my-5 space-y-3 rounded-2xl border border-white/20 p-5"><h3 className="font-bold">{stage.toUpperCase()} evidence</h3><p className="text-sm">Upload 3–5 clear photos showing every side, condition, packaging and identifying marks, plus a short video. Maximum 18 MB combined. Evidence is private.</p><label className="block">Photos<input className="block min-h-12 w-full py-3" type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>setPhotos(Array.from(e.target.files||[]))}/></label><label className="block">Video<input className="block min-h-12 w-full py-3" type="file" accept="video/mp4,video/webm" onChange={e=>setVideo(e.target.files?.[0]||null)}/></label><button className={button} disabled={busy} onClick={()=>void upload(stage)}>{busy?'Uploading / verifying…':'Submit evidence for verification'}</button></div>}
 {admin&&<div className="my-5 space-y-3 rounded-2xl bg-white/10 p-5"><h3 className="font-bold">Admin review</h3><textarea aria-label="Review reason" placeholder="Specific review reason (minimum 10 characters)" className="w-full rounded-xl bg-white p-3 text-black" value={reviewReason} onChange={e=>setReviewReason(e.target.value)}/>{data.evidence.filter(e=>e.review_status!=='VERIFIED'&&e.stage!=='dispute').map(e=><button key={e.id} disabled={busy||reviewReason.length<10} className={button} onClick={()=>void act('review_evidence',{evidenceId:e.id,reason:reviewReason})}>Approve reviewed {e.stage} evidence</button>)}{state==='DISPUTED'&&<><div className="grid grid-cols-2 gap-3"><label>Buyer refund (₹)<input type="number" value={refund} onChange={e=>setRefund(e.target.value)} className="min-h-12 w-full bg-white p-3 text-black"/></label><label>Deposit deduction (₹)<input type="number" value={deduction} onChange={e=>setDeduction(e.target.value)} className="min-h-12 w-full bg-white p-3 text-black"/></label></div><div className="flex flex-wrap gap-3">{['request_evidence','reject_claim','return'].map(outcome=><button key={outcome} className={button} disabled={busy||reviewReason.length<10} onClick={()=>void act('resolve_dispute',{outcome,reason:reviewReason,buyerRefundPaise:Math.round(Number(refund)*100),depositDeductionPaise:Math.round(Number(deduction)*100)})}>{outcome.replaceAll('_',' ')}</button>)}</div></>}{data.deal.secure_demo&&returnAdvance[state]&&<button className={button} disabled={busy} onClick={()=>void act('return_progress',{state:returnAdvance[state]})}>DEMO return: {returnAdvance[state]}</button>}{state==='RETURN_VERIFIED'&&<button className={button} disabled={busy} onClick={()=>void act('return_settle')}>Settle reviewed refunds</button>}</div>}
 <details className="my-5"><summary className="min-h-12 cursor-pointer py-3 font-bold">Evidence & payment records</summary>{data.payments.map(p=><p key={p.id}>{p.kind}: {rupees(p.amount_paise)} · {p.status}</p>)}{data.deposit&&<p>Security deposit: {data.deposit.status} · Deduction {rupees(data.deposit.deducted_paise)}</p>}{data.evidence.map(e=><article key={e.id} className="my-3 rounded-xl bg-white/5 p-4"><p><ShieldCheck className="inline h-4"/> {e.stage} · {e.review_status}</p><p className="my-2 text-sm break-words">{JSON.stringify(e.ai_result)}</p><div className="flex flex-wrap gap-2">{[...e.photos,e.video_path].map((p,i)=><button key={p} className="min-h-12 rounded-lg border border-white/20 px-3" onClick={()=>void view(p)}>{i===e.photos.length?'Video':`Photo ${i+1}`}</button>)}</div></article>)}</details><details><summary className="min-h-12 cursor-pointer py-3 font-bold">Delivery timeline</summary>{data.timeline.map(t=><p key={t.id} className="my-2 text-sm">{new Date(t.created_at).toLocaleString()} · {t.event_type.replaceAll('_',' ')}</p>)}</details>
 </>}
 </section>;
}
