"use client";
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {trustFetch,trustPost} from '@/lib/trust/client';
import SecureDeliveryPanel from '@/components/SecureDeliveryPanel';
type Review={score:number;risk_level:string;recommendation:string;reasons:string[];checks:Record<string,{status:string;reason:string}>;created_at:string};
type Listing={id:string;title:string;seller_id:string;status:string;safety_score:number|null;approval_method:string|null;created_at:string;listing_ai_reviews:Review[]};
type Risk={attribution?:string;attributed_by?:string;attributed_at?:string;attribution_reason?:string;id:string;call_id:string;reported_user_id:string|null;risk_type:string;confidence:string;snippet_excerpt:string;review_status:string;action_taken:string;created_at:string;analysis:unknown};
type Recording={id:string;call_id:string;uploaded_by:string;status:string;error:string|null};
type Audit={id:string;actor_id:string;action:string;entity_id:string;details:unknown;created_at:string};
type Data={identities:{id:string;full_name:string;verification_method:string;verification_status:string;identity_presence_status:string;verified_at:string}[];transcripts:{id:string;call_id:string;text:string;start_time:number;attribution_verified:boolean}[];listings:Listing[];risks:Risk[];deliveries:{id:string;deal_code:string;secure_state:string;secure_demo:boolean}[];recordings:Recording[];audit:Audit[]};
export default function TrustCenter(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('Listings'),[filter,setFilter]=useState('All'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState('');
const load=useCallback(async()=>{try{setData(await trustFetch('/api/trust/admin'));setError('');}catch(e){setError(e instanceof Error?e.message:'Review unavailable');}},[]);useEffect(()=>{void load();},[load]);
async function action(id:string,action:string,attribution?:string){setBusy(true);try{await trustPost('/api/trust/admin',{id,action,reason,attribution});await load();}catch(e){setError(e instanceof Error?e.message:'Review failed');}finally{setBusy(false);}}
async function recording(r:Recording){try{const result=await trustPost('/api/trust/media',{operation:'read',callId:r.call_id,recordingId:r.id});window.open(result.signedUrl,'_blank','noopener,noreferrer');}catch(e){setError(e instanceof Error?e.message:'Recording unavailable');}}
const btn='min-h-12 rounded-xl bg-lime-300 px-4 py-3 text-sm font-bold text-[#062016] disabled:opacity-40';
return <main className="min-h-screen bg-[#062016] px-5 py-12 text-white"><div className="mx-auto max-w-6xl"><Link className="inline-block min-h-12 underline" href="/admin">← Existing admin dashboard</Link><p className="text-xs tracking-widest text-lime-300">ECOMATCH · TRUST OPERATIONS</p><h1 className="my-4 text-4xl font-bold">Review with evidence.</h1><p className="max-w-2xl text-white/70">Listing checks, call safety and delivery disputes in one place. Every moderation decision records the reviewer and a reason.</p><nav className="my-6 flex flex-wrap gap-3">{['Listings','Call safety','Deliveries','Identity','Audit'].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?btn:'min-h-12 rounded-xl border border-white/30 px-4'}>{t}</button>)}<button className="min-h-12 px-4 underline" onClick={()=>void load()}>Refresh</button></nav>{error&&<p role="alert" className="my-4 rounded-xl bg-amber-100 p-4 text-amber-950">{error}</p>}
{['Listings','Call safety'].includes(tab)&&<label className="block max-w-2xl">Reason for your next moderation action<textarea className="my-3 w-full rounded-xl bg-white p-3 text-black" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Specific evidence and decision reason (at least 10 characters)"/></label>}
{tab==='Listings'&&<><div className="mb-5 flex flex-wrap gap-2">{['All','Auto Approved','Needs Review','Rejected','High Risk'].map(f=><button key={f} className={`min-h-12 rounded-full border px-4 ${filter===f?'border-lime-300 text-lime-300':'border-white/20'}`} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="grid gap-5 md:grid-cols-2">{data?.listings.filter(p=>filter==='All'||filter==='Auto Approved'&&p.approval_method==='ai_auto'||filter==='Needs Review'&&['pending','pending_review','changes_requested'].includes(p.status)||filter==='Rejected'&&p.status==='rejected'||filter==='High Risk'&&p.listing_ai_reviews.some(r=>r.risk_level==='HIGH')).map(p=>{const review=[...p.listing_ai_reviews].sort((a,b)=>b.created_at.localeCompare(a.created_at))[0];return <article key={p.id} className="rounded-2xl border border-white/20 bg-white/5 p-5"><p className="text-xs text-lime-300">{p.approval_method==='ai_auto'?'AI AUTO APPROVED':p.approval_method==='admin'?'ADMIN APPROVED':p.status.toUpperCase().replaceAll('_',' ')}</p><h2 className="mt-2 text-xl font-bold">{p.title}</h2><p className="my-3 text-sm break-all">Seller {p.seller_id}<br/>{new Date(p.created_at).toLocaleString()}</p><p>EcoMatch Safety Score: <strong>{p.safety_score??'Awaiting analysis'}</strong></p>{review&&<><p>{review.risk_level} · {review.recommendation}</p><ul className="my-3 list-disc pl-5">{review.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul><details><summary className="min-h-12 cursor-pointer py-3">Individual checks</summary>{Object.entries(review.checks).map(([k,c])=><p className="my-2 text-sm" key={k}><strong>{k}: {c.status}</strong> — {c.reason}</p>)}</details></>}<Link className="inline-block min-h-12 py-3 underline" href={`/product/${p.id}`}>View product</Link><div className="flex flex-wrap gap-2">{['approve','reject','changes'].map(a=><button key={a} className={btn} disabled={busy||reason.length<10||['sold','reserved'].includes(p.status)} onClick={()=>void action(p.id,a)}>{a==='changes'?'Request changes':a}</button>)}</div></article>;})}</div></>}
{tab==='Call safety'&&<><div className="space-y-5">{data?.risks.map(r=><article key={r.id} className="rounded-2xl border border-amber-300/30 p-5"><h2 className="font-bold">{r.risk_type} · {r.confidence}</h2><p className="my-2">{r.snippet_excerpt}</p><p className="text-sm">Call {r.call_id} · User {r.reported_user_id||'Identity unverified — review required'}</p><p className="my-2 text-xs">{new Date(r.created_at).toLocaleString()} · {r.review_status} · {r.action_taken}</p><details><summary className="min-h-12 py-3">Analysis evidence</summary><pre className="whitespace-pre-wrap break-all text-xs">{JSON.stringify(r.analysis,null,2)}</pre></details><details><summary className="min-h-12 py-3">Call transcript & recordings</summary>{data.transcripts.filter(t=>t.call_id===r.call_id).map(t=><p className="my-2" key={t.id}>{t.start_time}s · {t.text} ({t.attribution_verified?'verified speaker':'speaker unverified'})</p>)}{data.recordings.filter(v=>v.call_id===r.call_id).map(v=><button key={v.id} className={btn} onClick={()=>void recording(v)}>Play private recording</button>)}</details><div className="my-4 rounded-xl border border-white/20 p-4"><p className="mb-3 font-bold">Attribute violation after reviewing evidence</p><p className="mb-3 text-xs">{r.attribution||'Not attributed'} · Reviewer {r.attributed_by||'—'} · {r.attributed_at||'—'}</p><p className="mb-3 text-sm">{r.attribution_reason}</p><div className="flex flex-wrap gap-2">{['buyer','seller','unable_to_determine'].map(a=><button key={a} className={btn} disabled={busy||reason.trim().length<10} onClick={()=>void action(r.id,'attribute',a)}>{a.replaceAll('_',' ')}</button>)}</div></div><div className="flex flex-wrap gap-2">{['block','restore','warn','dismiss'].map(a=><button key={a} className={btn} disabled={busy||reason.length<10||(!r.reported_user_id&&a!=='dismiss')} onClick={()=>void action(r.id,a)}>{a==='block'?'Keep blocked':a==='restore'?'Restore account':a==='warn'?'Warn user':'Dismiss flag'}</button>)}</div></article>)}</div><h2 className="my-6 text-2xl font-bold">Private recordings</h2>{data?.recordings.map(r=><div key={r.id} className="my-3 flex flex-wrap items-center gap-3 rounded-xl bg-white/5 p-3"><span className="break-all text-sm">Call {r.call_id} · {r.status}{r.error&&` · ${r.error}`}</span><button className={btn} onClick={()=>void recording(r)}>Play with 60-second access link</button></div>)}</>}
{tab==='Deliveries'&&<><div className="grid gap-3 md:grid-cols-3">{data?.deliveries.map(d=><button className="min-h-20 rounded-2xl border border-white/20 p-4 text-left" key={d.id} onClick={()=>setSelected(d.id)}><strong>{d.deal_code}</strong><p>{d.secure_state.replaceAll('_',' ')}</p>{d.secure_demo&&<span className="text-amber-200">DEMO</span>}</button>)}</div>{selected&&<SecureDeliveryPanel key={selected} dealId={selected} userId="" admin/>}</>}
{tab==='Identity'&&<section><h2 className="my-4 text-2xl font-bold">IDENTITY VERIFICATION</h2>{data?.identities.map(p=><article key={p.id} className="my-3 rounded-xl border border-white/20 p-5"><h3 className="font-bold">{p.full_name||'EcoMatch member'}</h3><p>Method: {p.verification_method==='demo_identity_liveness'?'Demo Identity':p.verification_method?.includes('ekyc')?'UIDAI Offline e-KYC':p.verification_method||'None'}</p><p>Status: {p.verification_status==='verified_demo'?'DEMO VERIFIED · synthetic identity':p.verification_status}</p><p>Presence: {p.identity_presence_status||'Not recorded'}</p><p>Verified at: {p.verified_at?new Date(p.verified_at).toLocaleString():'—'}</p></article>)}</section>}
{tab==='Audit'&&data?.audit.map(a=><article key={a.id} className="my-3 rounded-xl bg-white/5 p-4"><p>{a.action} · {new Date(a.created_at).toLocaleString()}</p><p className="break-all text-xs">Actor {a.actor_id||'Server'} · {a.entity_id}</p><details><summary className="min-h-12 py-3">Details</summary><pre className="whitespace-pre-wrap break-all text-xs">{JSON.stringify(a.details,null,2)}</pre></details></article>)}
{data&&((tab==='Listings'&&!data.listings.length)||(tab==='Call safety'&&!data.risks.length)||(tab==='Deliveries'&&!data.deliveries.length))&&<p className="my-8 text-white/60">No records in this queue yet.</p>}</div></main>;
}
