"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {trustFetch,trustPost} from '@/lib/trust/client';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import MobileBottomNav from '@/components/MobileBottomNav';
import {Camera,ShieldCheck,CheckCircle2,FileCheck,RotateCcw} from 'lucide-react';
type DocResult={sessionId:string;expiresAt:string;challenge:string;method:'uidai_offline_ekyc'|'demo_identity_liveness';identity:{name:string;age?:number;dob?:string;referenceMasked:string;documentStatus?:string}};
type Detector=new(o?:object)=>{detect:(i:CanvasImageSource)=>Promise<unknown[]>};
const button='min-h-12 rounded-xl bg-emerald-400 px-5 py-3 text-sm font-bold text-[#03140e] disabled:opacity-40';
export default function VerifyIdentityPage(){
 const db=useMemo(()=>createClient(),[]),videoRef=useRef<HTMLVideoElement|null>(null),streamRef=useRef<MediaStream|null>(null),startedRef=useRef(0);
 const [demoAllowed,setDemoAllowed]=useState(false),[status,setStatus]=useState('unverified'),[savedPresence,setSavedPresence]=useState(''),[mode,setMode]=useState<'real'|'demo'>('real'),[xml,setXml]=useState<File|null>(null),[doc,setDoc]=useState<DocResult|null>(null),[busy,setBusy]=useState(false),[cameraOn,setCameraOn]=useState(false),[frameReady,setFrameReady]=useState(false),[confirmed,setConfirmed]=useState(false),[presence,setPresence]=useState(''),[faceResult,setFaceResult]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;void (async()=>{try{const [config,{data:{user}}]=await Promise.all([fetch('/api/identity/session',{cache:'no-store'}).then(r=>r.json()),db.auth.getUser()]);if(!alive)return;setDemoAllowed(config.demoEnabled===true);if(!user){setError('Please sign in to verify your identity.');return;}const {data,error}=await db.from('profiles').select('verification_status,identity_presence_status').eq('id',user.id).single();if(error)throw new Error('Identity setup is unavailable. Apply the identity migration first.');if(alive){setStatus(data.verification_status||'unverified');setSavedPresence(data.identity_presence_status||'');}}catch(e){if(alive)setError(e instanceof Error?e.message:'Unable to load identity settings');}finally{if(alive)setLoading(false);}})();return()=>{alive=false;streamRef.current?.getTracks().forEach(t=>t.stop());};},[db]);
 function stopCamera(){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCameraOn(false);setFrameReady(false);}
 function clear(){stopCamera();setDoc(null);setPresence('');setConfirmed(false);setFaceResult('');setError('');}
 async function verifyXml(){if(!xml)return;clear();setMode('real');setBusy(true);try{const form=new FormData();form.append('xml',xml);setDoc(await trustFetch('/api/identity/verify-aadhaar',{method:'POST',body:form}));}catch(e){setError(e instanceof Error?e.message:'Verification failed');}finally{setBusy(false);}}
 async function demo(action:'start'|'reset'){clear();setBusy(true);try{const result=await trustPost('/api/identity/demo',{action});if(action==='start'){setMode('demo');setDoc(result);}else{setStatus('unverified');setSavedPresence('');setMode('real');}}catch(e){setError(e instanceof Error?e.message:'Demo unavailable');}finally{setBusy(false);}}
 async function startCamera(){if(!doc)return;setError('');setPresence('');setConfirmed(false);setFaceResult('');try{stopCamera();const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:720}},audio:false});streamRef.current=stream;startedRef.current=Date.now();setCameraOn(true);}catch{setError('Camera access is required. Allow camera permission in your browser, then retry.');}}
 async function capture(){const video=videoRef.current;if(!video||!streamRef.current?.getVideoTracks().some(t=>t.readyState==='live')||video.videoWidth<100||Date.now()-startedRef.current<2000||!confirmed){setError('Wait for live frames, perform the challenge, then confirm it.');return;}setError('');setBusy(true);try{const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;const context=canvas.getContext('2d');if(!context)throw new Error('Camera preview is unavailable');context.drawImage(video,0,0);let result='camera_self_reported';const FaceDetector=(window as unknown as {FaceDetector?:Detector}).FaceDetector;
 if(FaceDetector){try{const faces=await new FaceDetector({fastMode:true,maxDetectedFaces:2}).detect(canvas);if(faces.length!==1){setError('Keep exactly one face clearly visible and retry.');return;}result='native_face_detected_self_reported_challenge';setFaceResult('One face detected by this browser. Challenge completion is self-confirmed.');}catch{setFaceResult('Face detection is unavailable. Camera presence and challenge completion are self-confirmed.');}}else setFaceResult('Camera frames available. DEMO/manual challenge confirmation — no automated face or movement detection.');
 setPresence(result);stopCamera();
 }catch(e){setError(e instanceof Error?e.message:'Camera check failed');}finally{setBusy(false);}}
 async function finish(){if(!doc||!presence)return;setBusy(true);setError('');try{const result=await trustPost('/api/identity/session',{sessionId:doc.sessionId,challenge:doc.challenge,presenceStatus:presence,presenceConfirmed:true});setStatus(result.status);setSavedPresence(result.presenceStatus);setDoc(null);}catch(e){setError(e instanceof Error?e.message:'Verification failed');}finally{setBusy(false);}}
 const done=status==='verified'||status==='verified_demo',isDemo=doc?.method==='demo_identity_liveness'||status==='verified_demo';
 return <main className="eco-page min-h-screen pb-24 text-white"><Navbar/><div className="relative mx-auto max-w-4xl px-5 pt-28"><p className="text-xs font-bold tracking-widest text-emerald-300">PHASE 8 · IDENTITY & TRUST</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">VERIFY ONCE.<br/><span className="text-emerald-400">SELL WITH HIGH TRUST.</span></h1><p className="mt-4 max-w-2xl text-sm text-white/70">Validate your signed UIDAI Offline e-KYC document, then complete a camera presence challenge. Camera checks here are not biometric face matching or spoof-proof liveness verification.</p>
 {demoAllowed&&<div className="my-6 rounded-2xl border border-amber-300/40 bg-amber-300/10 p-5"><strong className="text-amber-200">JUDGE DEMO MODE</strong><p className="mt-2 text-sm">Uses synthetic identity data. No UIDAI verification is performed.</p><p className="text-xs text-white/60">Presentation mode — synthetic identity, real camera presence flow.</p></div>}
 {error&&<p role="alert" className="my-5 rounded-xl border border-red-300/30 bg-red-950/50 p-4 text-red-100">{error}</p>}
 {loading?<p className="my-8">Loading identity settings…</p>:done?<section className="my-8 rounded-3xl border border-emerald-300/40 bg-[#06241a] p-8"><ShieldCheck className="h-12 w-12 text-emerald-300"/><span className={`mt-4 inline-block rounded-full px-4 py-2 text-sm font-bold ${isDemo?'bg-amber-200 text-amber-950':'bg-emerald-300 text-emerald-950'}`}>{isDemo?'DEMO VERIFIED':'UIDAI DOCUMENT VERIFIED'}</span><h2 className="my-5 text-2xl font-black">{isDemo?'IDENTITY VERIFIED FOR DEMO':'UIDAI Offline e-KYC verified'}</h2>{isDemo?<ul className="space-y-3"><li>✓ Demo Identity Validated</li><li>✓ Live Presence Challenge Completed</li><li>✓ EcoMatch Demo Trust Verification Complete</li></ul>:<p>Digital signature verified against the UIDAI certificate. Camera challenge completion was self-reported.</p>}<p className="mt-5 text-sm text-white/70">EcoMatch combines identity validation and live-presence checks to reduce anonymous marketplace fraud.</p><p className="mt-3 text-xs text-white/60">Presence: {savedPresence.replaceAll('_',' ')||'No presence metadata available'}. No biometric identity match was performed.{isDemo?' Demo status does not grant genuine UIDAI privileges.':''}</p><Link href="/profile" className="mt-5 inline-flex min-h-12 items-center underline">View profile →</Link>{demoAllowed&&isDemo&&<button className={`${button} ml-4`} disabled={busy} onClick={()=>void demo('reset')}><RotateCcw className="mr-2 inline h-4"/>Reset Demo Verification</button>}</section>:<>
 <div className="my-6 flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={()=>{clear();setMode('real');}}>Verify with UIDAI Offline e-KYC</button>{demoAllowed&&<button className="min-h-12 rounded-xl border border-amber-300 bg-amber-300/10 px-5 py-3 font-bold text-amber-100 disabled:opacity-40" disabled={busy} onClick={()=>void demo('start')}>Try Demo Verification</button>}</div>
 <div className="my-6 grid grid-cols-3 gap-2 text-center text-xs sm:text-sm">{[['Identity',!!doc],['Live Presence',!!presence],['Trust Verification',false]].map(([label,complete])=><div key={String(label)} className={`rounded-xl border p-4 ${complete?'border-emerald-400 bg-emerald-400/10':'border-white/15'}`}>{complete?'✓ ':''}{label}</div>)}</div>
 <section className="my-6 rounded-3xl border border-emerald-500/25 bg-[#061e16] p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><FileCheck/>01 · {mode==='demo'?'Synthetic Demo Identity':'UIDAI Paperless Offline e-KYC'}</h2>{mode==='real'&&<><p className="my-3 text-sm text-white/60">Upload the extracted XML from MyAadhaar, not its password-protected ZIP. Raw XML and identity photos are not stored.</p><input aria-label="UIDAI Offline XML" type="file" accept=".xml,application/xml,text/xml" disabled={busy} onChange={e=>{clear();setXml(e.target.files?.[0]||null);}} className="my-3 block min-h-12 w-full rounded-xl border border-white/20 p-3"/><button className={button} disabled={busy||!xml} onClick={()=>void verifyXml()}>{busy?'Validating…':'Verify e-KYC XML'}</button></>}{doc&&<div className="mt-5 rounded-2xl border border-emerald-300/30 p-5"><p className="font-bold text-emerald-200">{doc.identity.name}</p>{isDemo&&<p>Age: {doc.identity.age}</p>}<p>Identity Reference: {doc.identity.referenceMasked}</p><p>{isDemo?'Document Status: Synthetic Demo Identity':'UIDAI digital signature verified'}</p><p className="mt-2 text-xs text-white/60">Session expires at {new Date(doc.expiresAt).toLocaleTimeString()}</p></div>}</section>
 <section className="my-6 rounded-3xl border border-emerald-500/25 bg-[#061e16] p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><Camera/>02 · Live Camera Presence Challenge</h2><p className="my-3 text-sm text-white/60">Uses your real camera. Frames stay in this browser. Native face detection is used where available; the requested movement is self-confirmed.</p>{!cameraOn&&!presence&&<button className={button} disabled={!doc||busy} onClick={()=>void startCamera()}>Start Live Camera</button>}{cameraOn&&<div className="space-y-4"><p className="text-emerald-300">✓ Camera Started {frameReady?'→ Live Frames Detected':''}</p><div className="max-w-lg overflow-hidden rounded-2xl border border-emerald-300/40 bg-black"><video ref={node=>{videoRef.current=node;if(node&&streamRef.current&&node.srcObject!==streamRef.current){node.srcObject=streamRef.current;void node.play().catch(()=>setError('Press play to start your camera preview.'));}}} autoPlay playsInline muted onLoadedData={()=>setFrameReady(true)} className="aspect-video w-full object-cover"/></div><p className="rounded-xl bg-amber-200/10 p-4 text-amber-100">Challenge: <strong>{doc?.challenge}</strong></p><label className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="h-5 w-5"/>I performed this challenge. This is a manual confirmation, not automatic biometric verification.</label><button className={button} disabled={!frameReady||!confirmed||busy} onClick={()=>void capture()}>Confirm challenge & check camera frame</button></div>}{presence&&<div className="rounded-xl bg-emerald-400/10 p-4"><p className="font-bold text-emerald-200"><CheckCircle2 className="mr-2 inline h-5"/>Challenge Completed → Presence Check Complete</p><p className="mt-2 text-sm text-white/70">{faceResult}</p><button className="mt-2 min-h-12 underline" disabled={busy} onClick={()=>void startCamera()}>Repeat camera challenge</button></div>}</section>
 <section className="my-6 rounded-3xl border border-emerald-300/40 bg-[#072a1d] p-6"><h2 className="text-lg font-bold">03 · {isDemo?'Activate DEMO VERIFIED badge':'Complete identity verification'}</h2><button className={`${button} mt-5`} disabled={!doc||!presence||busy} onClick={()=>void finish()}>{busy?'Saving…':isDemo?'Complete Demo Verification':'Complete Identity Verification'}</button>{demoAllowed&&mode==='demo'&&<button className="ml-3 min-h-12 underline" disabled={busy} onClick={()=>void demo('reset')}>Reset Demo Verification</button>}</section>
 </>}
 </div><Footer/><MobileBottomNav/></main>;
}
