import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { Presentation, PresentationFile } from '@oai/artifact-tool';
const D='C:/Users/hindj/jaavaa/ecomatch', S='C:/Users/hindj/.codex/plugins/cache/openai-primary-runtime/presentations/26.915.20218/skills/presentations', T=path.join(D,'.pitch-build-20260929'), O=path.join(D,'output','EcoMatch_Segue_3_Grand_Finale_Pitch_Final.pptx');
const SCREEN=await fs.readFile(path.join(T,'secure-delivery-live.png'));
const {resolvePresentationFont,finalizePresentation}=await import(pathToFileURL(path.join(S,'container_tools/artifact_tool_utils.mjs')).href); const F=resolvePresentationFont(); const p=Presentation.create({slideSize:{width:1280,height:720}}); const C={d:'#0B2118',i:'#08251A',l:'#B9FF66',c:'#F4F4E9',m:'#62766C',w:'#FFFFFF',a:'#F5A23A',g:'#DFF7E7',b:'#DDEEFF',s:'#FFE7BB'};
const add=(bg=C.c)=>{const s=p.slides.add();s.background.fill=bg;return s}; const B=(s,x,y,w,h,f,r=20)=>s.shapes.add({geometry:r?'roundRect':'rect',position:{left:x,top:y,width:w,height:h},fill:f,line:{fill:'none',width:0},borderRadius:r?'rounded-2xl':undefined}); const X=(s,t,x,y,w,h,o={})=>{const q=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});q.text=t;q.text.style={typeface:F,fontSize:o.z??22,bold:o.bold??false,color:o.col??C.i,alignment:o.align??'left',autoFit:'shrink'};return q}; const L=(s,x,y,w,h,c=C.l)=>B(s,x,y,w,h,c,0); const N=(s,t)=>s.speakerNotes.textFrame.setText(t);
function H(s,n,t,sub=''){X(s,`0${n}`,72,54,60,22,{z:13,bold:true,col:C.a});X(s,t,72,84,1020,58,{z:38,bold:true});if(sub)X(s,sub,72,150,1010,35,{z:17,col:C.m});L(s,72,205,1136,2,C.i);X(s,'EcoMatch  |  Segue 3.0',1040,54,170,20,{z:11,bold:true,col:C.m,align:'right'})}
function HD(s,n,t,sub=''){X(s,`0${n}`,72,54,60,22,{z:13,bold:true,col:C.a});X(s,t,72,84,1020,58,{z:38,bold:true,col:C.w});if(sub)X(s,sub,72,150,1010,35,{z:17,col:'#B8CBBF'});L(s,72,205,1136,2,'#31583D');X(s,'EcoMatch  |  Segue 3.0',1040,54,170,20,{z:11,bold:true,col:'#9FB7AA',align:'right'})}
// 1
{let s=add(C.d);L(s,74,74,9,500);X(s,'ECOMATCH',112,74,250,28,{z:17,bold:true,col:C.l});X(s,'A circular marketplace\nfor cleaner, more\nresourceful cities',112,145,760,255,{z:62,bold:true,col:C.w});X(s,'Giving usable materials, equipment and industrial surplus a trusted second life.',118,432,640,62,{z:22,col:'#D7E7DF'});B(s,882,140,260,260,C.l,150);X(s,'11',927,190,170,100,{z:92,bold:true,col:C.d,align:'center'});X(s,'Sustainable Cities\nand Communities',894,320,235,54,{z:17,bold:true,col:C.d,align:'center'});X(s,'Segue 3.0 Finale  |  Team EcoMatch\nJanit Kumar Hind · Krish Tiwari · Jeetu Yadav · Khushboo Sharma · Khushi Kumari',112,600,880,48,{z:15,col:'#B8CBBF'});X(s,'Live product\neco-match-sepia.vercel.app',965,604,205,42,{z:13,bold:true,col:C.l,align:'right'});N(s,'Opening: EcoMatch helps cities recover value before usable material becomes waste. Show the live product after the pitch.')}
// 2
{let s=add();H(s,2,'The urban surplus problem','Usable assets are difficult to discover, verify and move before they become waste.');X(s,'A city already has the material it needs.\nIt is simply locked inside offices, warehouses and institutions.',72,250,570,150,{z:35,bold:true});B(s,710,236,440,292,C.w,28);X(s,'What happens today',750,268,300,28,{z:18,bold:true,col:C.m});[['1','A seller has usable surplus but no trusted buyer'],['2','A buyer cannot assess condition, location or fair value'],['3','Transport and handover feel risky, so reuse stalls']].forEach(([n,t],i)=>{B(s,750,320+i*62,34,34,C.i,17);X(s,n,758,328+i*62,18,16,{z:14,bold:true,col:C.w,align:'center'});X(s,t,802,321+i*62,300,38,{z:16})});X(s,'Result: material loses value, disposal pressure grows and cities miss a local reuse opportunity.',72,560,1000,42,{z:22,bold:true,col:'#31583D'});N(s,'Problem framing. No local waste statistic is claimed without a source.')}
//3
{let s=add(C.d);HD(s,3,'Reuse before disposal','EcoMatch creates a local path for usable assets before they enter the waste stream.');X(s,'“Reduce the adverse per capita environmental impact of cities … paying special attention to air quality and municipal and other waste management.”',90,250,820,130,{z:31,bold:true,col:C.w});B(s,940,240,198,198,C.a,99);X(s,'11.6',965,280,148,52,{z:45,bold:true,col:C.d,align:'center'});X(s,'Waste management\n& city impact',962,348,153,40,{z:15,bold:true,col:C.d,align:'center'});X(s,'EcoMatch acts upstream: it makes reuse a practical option before a usable item reaches the waste stream.',90,480,865,65,{z:24,col:C.g});X(s,'Source: United Nations Sustainable Development Goal 11, Target 11.6',90,637,720,17,{z:11,col:'#AAC0B3'});N(s,'Source: https://sdgs.un.org/goals/goal11. Target 11.6 wording. EcoMatch contribution is an intended pathway, not a measured claim.')}
//4
{let s=add();H(s,4,'Three users, one broken exchange','Each stakeholder sees the same surplus through a different risk.');[['Material owner','“I want to recover value, but I need a serious buyer and safe pickup.”',C.g],['Buyer / recycler','“I need condition, price and location clarity before committing.”',C.b],['City ecosystem','“More assets should circulate locally before they become disposal work.”',C.s]].forEach(([a,b,c],i)=>{let x=72+i*380;B(s,x,270,330,235,c,26);X(s,a,x+26,304,270,30,{z:21,bold:true});X(s,b,x+26,358,275,95,{z:19});X(s,`0${i+1}`,x+26,462,60,22,{z:12,bold:true,col:C.m})});X(s,'EcoMatch gives each side the information and protocol needed to progress to a safe exchange.',72,565,1030,42,{z:24,bold:true,col:'#31583D'});N(s,'User problem model based on product design observation. No customer validation count is claimed.')}
//5
{let s=add(C.d);HD(s,5,'EcoMatch turns scattered surplus into a trusted exchange','LIST  →  MATCH  →  VERIFY  →  DEAL  →  MOVE  →  HANDOVER  →  OWNERSHIP RECORD');[['List','Photos and product details become a structured listing'],['Evaluate','AI assistance, condition notes and fair-price context'],['Deal','Private negotiation with verified identity signals'],['Move','Seller pickup and buyer destination create a route estimate'],['Complete','Evidence, QR/OTP handover and ledger record']].forEach(([a,b],i)=>{let y=255+i*70;B(s,100,y,112,40,C.l,20);X(s,`0${i+1}`,132,y+10,46,16,{z:14,bold:true,col:C.d,align:'center'});X(s,a,244,y+2,180,26,{z:21,bold:true,col:C.w});X(s,b,436,y+4,630,31,{z:17,col:'#C9D9D1'});if(i<4)L(s,154,y+42,2,28,'#5D8F67')});X(s,'One platform for discovery, confidence and accountable handover.',100,625,850,32,{z:20,bold:true,col:C.l});N(s,'Core EcoMatch workflow. Demo it live after slide 8.')}
//6
{let s=add();H(s,6,'This is not a concept. EcoMatch is live.','A deployed product connects discovery to a secure deal room.');[['Marketplace','Search reusable materials, filter by location and view seller signals'],['AI tools','Classify materials and support clearer product information'],['Deal room','Agree terms, chat privately and choose fulfilment'],['Secure delivery','Route-based estimate, payment simulation, QR/OTP handover'],['Ledger','Record completion and ownership transfer'],['Trust Center','Admin review for listings, delivery cases and disputes']].forEach(([a,b],i)=>{let col=i%3,row=Math.floor(i/3),x=72+col*382,y=248+row*170;B(s,x,y,340,135,[C.g,C.b,C.s][col],22);X(s,`0${i+1}`,x+22,y+20,35,18,{z:12,bold:true,col:C.m});X(s,a,x+22,y+48,275,26,{z:20,bold:true});X(s,b,x+22,y+80,285,42,{z:14,col:C.m})});X(s,'Live demo: eco-match-sepia.vercel.app',72,618,500,24,{z:16,bold:true,col:'#31583D'});B(s,680,225,490,350,C.i,24);s.images.add({blob:SCREEN,contentType:'image/png',alt:'Live EcoMatch Secure Delivery screen',fit:'cover',position:{left:690,top:235,width:470,height:330},geometry:'roundRect',borderRadius:'rounded-2xl'});N(s,'Product proof based on deployed EcoMatch application. Live URL: https://eco-match-sepia.vercel.app/')}
//7
{let s=add(C.d);HD(s,7,'A marketplace is easy to build. Trust is harder.','VERIFY THE PERSON  →  VERIFY THE PRODUCT  →  SECURE THE MEETING  →  VERIFY THE EXCHANGE  →  TRACE THE OWNERSHIP');[['Seller','Saved pickup location\nProduct price from deal'],['EcoMatch','Road distance\nWeight & vehicle logic'],['Buyer','Current location or\nsearched destination']].forEach(([a,b],i)=>{let x=100+i*430;B(s,x,270,220,124,'#143A2A',22);X(s,a,x+26,298,130,25,{z:20,bold:true,col:C.l});X(s,b,x+26,336,160,42,{z:15,col:C.w});if(i<2)L(s,x+220,330,210,4)});X(s,'Estimated total = product price + delivery estimate + 10% delivery service fee',170,500,900,38,{z:25,bold:true,col:C.w,align:'center'});X(s,'Carrier booking and payment stay labelled as simulation until partner and gateway credentials are connected.',170,560,900,32,{z:16,col:'#C9D9D1',align:'center'});N(s,'Integrity controls: browser does not choose pickup, product price or distance. Real carrier booking and payment are not claimed.')}
//8
{let s=add();H(s,8,'Trust moves the exchange forward','EcoMatch separates the signals a buyer needs before agreeing to a handover.');[['Identity','KYC status makes the counterparty visible'],['Listing','Images, condition and admin review support listing quality'],['Transaction','Private deal terms and payment state create a shared record'],['Handover','Evidence plus a time-bound QR/OTP completes the physical exchange']].forEach(([a,b],i)=>{let x=72+i*280;L(s,x,262,92,8,[C.l,C.a,'#73C6F5','#8F8ADF'][i]);X(s,`0${i+1}`,x,292,70,20,{z:12,bold:true,col:C.m});X(s,a,x,328,230,28,{z:22,bold:true});X(s,b,x,375,240,74,{z:16,col:C.m})});X(s,'The aim: make the transaction inspectable, accountable and easier to complete.',72,570,950,40,{z:26,bold:true,col:'#31583D'});N(s,'Do not call every user verified. The platform displays distinct identity, listing and handover signals.')}
//9
{let s=add(C.d);HD(s,9,'Impact measurement begins with every completed exchange','We will report what moves through EcoMatch rather than make unverified impact claims.');[['Assets reused','Count of completed item or material exchanges'],['Material diverted','Seller-entered, verified weight category or confirmed weight'],['Local circulation','Route distance and buyer/seller locality'],['Trust quality','Verified listings, completed handovers and dispute resolution time']].forEach(([a,b],i)=>{let x=82+(i%2)*560,y=250+Math.floor(i/2)*160;B(s,x,y,500,125,'#143A2A',20);X(s,a,x+25,y+25,420,25,{z:21,bold:true,col:C.l});X(s,b,x+25,y+62,420,40,{z:16,col:'#D9E8E0'})});X(s,'Pilot goal: establish a credible baseline before publishing environmental savings.',82,610,1000,30,{z:20,bold:true,col:C.g});N(s,'All impact measures are proposed product metrics. No environmental savings figures are claimed until measurement methodology and pilot data are available.')}
//10
{let s=add();H(s,10,'A practical path to city-scale reuse','Start with dense supply, learn from exchanges, then connect institutions and logistics.');[['Pilot','Work with campuses, offices and local recyclers. Validate listing quality and successful handovers.'],['Network','Build repeat buyer-seller communities around material streams and local areas.'],['Institutional','Offer reporting, controlled workflows and reuse insights to organizations and city partners.']].forEach(([a,b],i)=>{let x=92+i*380;B(s,x,285,320,220,[C.g,C.b,C.s][i],25);X(s,`PHASE ${i+1}`,x+24,312,150,18,{z:12,bold:true,col:C.m});X(s,a,x+24,350,250,30,{z:24,bold:true});X(s,b,x+24,401,260,76,{z:16,col:C.m})});X(s,'Revenue can come from transaction services and institutional workflow tools after the pilot proves exchange quality.',92,570,1010,40,{z:21,bold:true,col:'#31583D'});N(s,'Roadmap is a plan, not a forecast. Avoid revenue claims until pilot metrics and pricing validation are available.')}
//11
{let s=add(C.d);X(s,'THE ASK',92,80,220,25,{z:15,bold:true,col:C.l});X(s,'Help us make reuse\nvisible, trusted and\nworth choosing.',92,140,770,220,{z:60,bold:true,col:C.w});X(s,'EcoMatch\\nGiving usable resources a trusted second life.',96,410,685,60,{z:22,col:'#D7E7DF'});B(s,910,170,200,200,C.l,100);X(s,'LIVE\nDEMO',940,230,140,66,{z:28,bold:true,col:C.d,align:'center'});X(s,'eco-match-sepia.vercel.app',848,420,335,24,{z:17,bold:true,col:C.l,align:'center'});X(s,'EcoMatch  |  Segue 3.0 Finale',96,627,370,20,{z:13,col:'#AAC0B3'});N(s,'Closing ask: invite judges to open the deployed app. End, then switch to the live product walkthrough.')}
await fs.mkdir(T,{recursive:true});const draft=path.join(T,'candidate-ecomatch-segue3.pptx');await (await PresentationFile.exportPptx(p)).save(draft);const result=await finalizePresentation({explicitTotalSlideCount:11,workspaceDir:D,candidatePath:draft,finalPath:O,pythonExecutable:'C:/Users/hindj/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:path.join(S,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(S,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],fontPolicy:{basis:'design',families:[F]},verifyArtifactToolImport:true,receiptPath:path.join(T,'validation-v4.json')});console.log(JSON.stringify({font:F,output:O,result},null,2));





